# Generated by Django 3.2.4 on 2022-01-30 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('duration', models.FloatField(help_text='in hours')),
                ('type', models.TextField(choices=[('action', 'Action'), ('science_fiction', 'Science Fiction'), ('comedy', 'Comedy'), ('terror', 'Terror'), ('drama', 'Drama'), ('suspense', 'Suspense'), ('romantic', 'Romantic')])),
                ('producers', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
