# Generated by Django 3.2.4 on 2022-01-30 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='owner',
        ),
    ]
